### ISSUE TITLE
Named fenced code blocks are not recognized

### ISSUE THREAD

**Issue by haykam821** [Lachcim/css-irl-bot#5]
Named fenced code blocks, like the following example, are not recognized as code blocks by the bot:

````md
```css
*::before {
    content: 'named fenced code block';
}
```
````

However, regular fenced code blocks, inline code, and 4-spaced code blocks are recognized, and like these 3, are all officially recognized by Reddit's Markdown parser as code formatting.

**Comment by Lachcim** [comment]
First of all, excellent catch, thank you for that! I have observed the bug with the syntax provided in your issue.

However, and this may surprise you, reddit does not in fact support this syntax you speak of. On old.reddit.com and i.reddit.com, what you describe as "named code blocks" is simply displayed as **inline plain-text code** with the language name as the first word. This leads me to believe that it is a client-specific feature on your end.

The problem here is that the bot's internal Markdown parser, mistune, does support this feature, which upsets the code-seeking regex and introduces a disparity between what the bot sees and what the users see.

Two solutions are viable:
* Update the regex to account for `class="lang-css"` and similar HTML, preserving the disparity
* Find a way to disable the triple-backtick syntax in mistune

I shall look into this as soon as I find the time.

**Comment by haykam821** [comment]
The Reddit redesign and the official Reddit for iOS client support named fenced code blocks. I think old and mobile reddit use an outdated version of the parser.

**Comment by Lachcim** [comment]
I decided against handling fenced code because it is not documented on the official [commenting wiki page](https://old.reddit.com/wiki/commenting). If reddit remained open-source to this day, I would have opened an issue demanding to fix this discrepancy between Markdown renderers.

**Comment by haykam821** [comment]
That wiki page says:

> This page is no longer updated.
> 
> For more up to date information go here: https://www.reddit.com/wiki/markdown

[The new wiki page](https://www.reddit.com/wiki/markdown#wiki_code_blocks_and_inline_code) documents fenced code blocks. It does not show named fenced code blocks, despite being supported by the redesign and app.

**Comment by Lachcim** [comment]
You know, I am constantly amazed by the terrible decisions made by reddit admins.

I've re-implemented fenced code block parsing and commented out the previous solution in case it's needed in the future. For the sake of clarity, this is the difference in code block rendering across different reddit versions:

![codediff](https://user-images.githubusercontent.com/15709471/69834141-df2da300-1238-11ea-911e-99bf4679987b.png)

@haykam821, I noticed that in one of your replies to my /r/css_irl post, you told us to ignore the tilde syntax as "reddit doesn't seem to support it". May I ask what you meant by that? It seems to be working on my client (new.reddit.com on Chrome).
